version: '2'
services:
  mysql:
    build: ./mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  flask:
    build: ./flask
    ports:
      - 5000:5000
    volumes:
      - ./src:/var/www/flask
    links:
      - mysql
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: init.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0
