version: "2"
services:
  mysql:
    build: ./mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  fastapi:
    build: ./fastapi
    ports:
      - 8000:8000
    volumes:
      - ./src:/var/www/fastapi
    links:
      - mysql
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: init.py
      FLASK_ENV: development
    command: uvicorn main:app --reload --host 0.0.0.0
